apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeip.name" . }}-config
  labels:
    {{- include "kubeip.labels" . | nindent 4 }}
  namespace: kube-system
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: {{ .Values.cluster.name }}
  KUBEIP_NODEPOOL: {{ .Values.cluster.public_nodepool }}
  KUBEIP_FORCEASSIGNMENT: "true"
  KUBEIP_ADDITIONALNODEPOOLS: ""
  KUBEIP_TICKER: "5"
  KUBEIP_ALLNODEPOOLS: "false"
  KUBEIP_ORDERBYLABELKEY: "priority"
  KUBEIP_ORDERBYDESC: "true"
  KUBEIP_COPYLABELS: "false"
  KUBEIP_CLEARLABELS: "false"
  KUBEIP_DRYRUN: "false"