kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "traefik.name" . }}-role-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "traefik.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "traefik.name" . }}-account
    namespace: default
