apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.name" . }}-web-service

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "traefik.name" . }}
