apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "whoami.name" . }}-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "whoami.name" . }}-svc
            port:
              name: web
