apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.name" . }}-svc

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: {{ include "whoami.name" . }}